# Generated by Django 2.1.7 on 2019-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Category', max_length=255)),
                ('slug', models.CharField(help_text='Category slug', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_id', models.CharField(help_text='Yelp ID', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of Restaurant', max_length=255)),
                ('is_closed', models.BooleanField(default=False, help_text='Whether business has been closed permanently.')),
                ('snippet', models.CharField(help_text='Snippet about the restaurant.', max_length=255)),
                ('image_url', models.URLField(help_text='Image URL from Yelp')),
                ('phone', models.CharField(help_text='Formatted phone number for backend', max_length=20)),
                ('display_phone', models.CharField(help_text='Display phone number for HTML', max_length=30)),
                ('url', models.URLField(help_text='Yelp URL for the page')),
                ('review_count', models.IntegerField(help_text='Number of reviews.', null=True)),
                ('rating', models.FloatField(help_text='Yelp Rating')),
                ('rating_img', models.URLField(help_text='Rating Image URL from Yelp')),
                ('display_address', models.TextField(help_text='Display Address for Restaurant')),
                ('city', models.CharField(help_text='City', max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(help_text='Zip code', max_length=10)),
                ('latitude', models.FloatField(help_text='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude')),
                ('categories', models.ManyToManyField(help_text='Categories that the restaurant belongs to', to='demo.Category')),
            ],
        ),
    ]
