# Generated by Django 2.1.7 on 2019-03-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_restaurant_rating_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='state',
        ),
    ]
