# Generated by Django 2.1.7 on 2019-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_restaurant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(help_text='Yelp ID', max_length=255),
        ),
    ]
